examples: ping1d-servo: create new example
bluerobotics/ping-arduino pull request #40
Opened 2022-03-13 06:07 UTC by ES-Alexander

Context in [this forum thread](https://discuss.bluerobotics.com/t/using-ping1d-and-servo-with-arduino-nano-every/11715)

2022-03-14 12:13 UTC, patrickelectric requested changes

2022-03-14 12:13 UTC, patrickelectric commented on examples/ping1d-servo/ping1d-servo.ino
> +    moveServo(pos);
Please fix the code style, you can use [clang-format](https://zed0.co.uk/clang-format-configurator/) for it.

2022-03-14 12:13 UTC, patrickelectric commented on examples/ping1d-servo/ping1d-servo.ino
> +int max_angle;
These variables can be moved inside the necessary scope, don't need to be global.

2022-03-14 12:13 UTC, patrickelectric commented on examples/ping1d-servo/ping1d-servo.ino
> +int min_angle = 0;
There is a mix of camelCase and snake_case here, check the others examples for consistency.

2025-12-05 19:57 UTC, ES-Alexander commented
@patrickelectric I found this in my unmerged PRs list, so I finally addressed your review comments 😅

2025-12-06 00:35 UTC, patrickelectric approved these changes

2025-12-06 00:35 UTC, merged